### ISSUE TITLE
Call for Developers

### ISSUE THREAD

**Issue by livinginformation** [monero-project/kovri#530] opened 2017-01-21 22:15 UTC
**By submitting this issue, I confirm the following:**

- I have read and understood the [contributor guide](https://github.com/monero-project/kovri/blob/master/doc/CONTRIBUTING.md).
- I have checked that the issue I am reporting can be replicated or that the feature I am suggesting is not present.
- I have checked opened or recently closed [pull requests](https://github.com/monero-project/kovri/pulls) for existing solutions/implementations to my issue/suggestion.

*Place an X inside the bracket to confirm*
- [X] I confirm.

---

This issue filed at the behest of Anonimal. 

https://www.youtube.com/watch?v=KMU0tzLwhbE

**Comment by anonimal** [comment] 2017-01-23 23:24
Thanks for opening this @livinginformation and for bringing this up on IRC.

Since this is a duplicate of #159, I'm going to close both of these issues and officially move the issue to https://github.com/monero-project/meta/issues/43.

**Closed by anonimal** 2017-01-23 23:24 UTC
