### ISSUE TITLE
Unable to build on RPi 3

### ISSUE THREAD

**Issue by scoobybejesus** [monero-project/kovri#476] opened 2016-11-22 00:37 UTC
**By submitting this issue, I confirm the following:**

- I have read and understood the [contributor guide](https://github.com/monero-project/kovri/blob/master/doc/CONTRIBUTING.md).
- I have checked that the issue I am reporting can be replicated or that the feature I am suggesting is not present.
- I have checked opened or recently closed [pull requests](https://github.com/monero-project/kovri/pulls) for existing solutions/implementations to my issue/suggestion.

*Place an X inside the bracket to confirm*
- [ x] I confirm.

---

Unable to build on Raspberry Pi 3 running Raspbian Lite.  See the following final output:

pi@raspberrypi:~ $ rm -fr kovri/ && git clone --recursive https://github.com/monero-project/kovri && cd kovri/ && make && make install-resources
Cloning into 'kovri'...
remote: Counting objects: 16552, done.
remote: Compressing objects: 100% (199/199), done.
remote: Total 16552 (delta 106), reused 0 (delta 0), pack-reused 16353
Receiving objects: 100% (16552/16552), 7.12 MiB | 6.45 MiB/s, done.
Resolving deltas: 100% (11676/11676), done.
Submodule 'deps/cpp-netlib' (https://github.com/anonimal/cpp-netlib.git) registered for path 'deps/cpp-netlib'
Submodule 'deps/cryptopp' (https://github.com/anonimal/cryptopp.git) registered for path 'deps/cryptopp'
Cloning into '/home/pi/kovri/deps/cpp-netlib'...
Cloning into '/home/pi/kovri/deps/cryptopp'...
Submodule path 'deps/cpp-netlib': checked out 'ac5fd8852d2e54fe3d6b210261b0b10fc3b01d68'
Submodule 'deps/asio' (https://github.com/chriskohlhoff/asio.git) registered for path 'deps/cpp-netlib/deps/asio'
Submodule 'deps/cxxopts' (https://github.com/jarro2783/cxxopts.git) registered for path 'deps/cpp-netlib/deps/cxxopts'
Submodule 'deps/googlemock' (https://github.com/google/googlemock.git) registered for path 'deps/cpp-netlib/deps/googlemock'
Submodule 'deps/googletest' (https://github.com/google/googletest.git) registered for path 'deps/cpp-netlib/deps/googletest'
Submodule 'libs/network/doc/_ext/breathe' (https://github.com/michaeljones/breathe.git) registered for path 'deps/cpp-netlib/libs/network/doc/_ext/breathe'
Cloning into '/home/pi/kovri/deps/cpp-netlib/deps/asio'...
Cloning into '/home/pi/kovri/deps/cpp-netlib/deps/cxxopts'...
Cloning into '/home/pi/kovri/deps/cpp-netlib/deps/googlemock'...
Cloning into '/home/pi/kovri/deps/cpp-netlib/deps/googletest'...
Cloning into '/home/pi/kovri/deps/cpp-netlib/libs/network/doc/_ext/breathe'...
Submodule path 'deps/cpp-netlib/deps/asio': checked out '66e76b9e4252ff4681227d0d8e34374ec1fa20e5'
Submodule path 'deps/cpp-netlib/deps/cxxopts': checked out 'aec97a6f53c3486fc51e0d9857f10b683180d668'
Submodule path 'deps/cpp-netlib/deps/googlemock': checked out 'f7d03d2734759ee12b57d2dbcb695607d89e8e05'
Submodule path 'deps/cpp-netlib/deps/googletest': checked out 'd225acc90bc3a8c420a9bcd1f033033c1ccd7fe0'
Submodule path 'deps/cpp-netlib/libs/network/doc/_ext/breathe': checked out '853385ef4f0c3dd126887750e20d5f7456065998'
Submodule path 'deps/cryptopp': checked out 'c621ce053298fafc1e59191079c33acd76045c26'
mkdir -p deps/cpp-netlib/build/
cd deps/cpp-netlib/build/ && cmake  -D CMAKE_BUILD_TYPE=Debug -D CPP-NETLIB_BUILD_TESTS=OFF -D CPP-NETLIB_BUILD_EXAMPLES=OFF ../ && make
Segmentation fault
Makefile:95: recipe for target 'dependencies' failed
make: *** [dependencies] Error 139

**Comment by anonimal** [comment] 2016-11-22 12:32
Have you satisfied all dependencies? How much swap space do you have? gcc or clang? Version numbers for cmake and compiler? What source(s) are you pulling from with apt?

I cannot reproduce with our rpi3. @danrmiller, does this issue look familiar to you?

**Comment by scoobybejesus** [comment] 2016-11-22 15:24
I performed all the steps for Debian Stable, including creating and editing custom.pref and custom.list.  In `/etc/apt/sources.list.d/custom.list`, my mirror is:
http://mirrordirector.raspbian.org/raspbian/

I copied and pasted the required dependencies, which ran/installed without error; and I copied and pasted the clang dependency, though I changed it slightly to `$ sudo apt-get -t testing install clang-3.5`.  Prior to running make, I entered/ran `export CC=clang-3.5 CXX=clang++-3.5`.

I just ran `cat /proc/meminfo`, and it says I have SwapTotal and SwapFree of 626680 kB.

I don't know if it would be the right command, but I tried to run `cmake -version` and `cmake --version`, and then `cmake --help` and just `cmake`, and they all come back with "Segmentation fault."

**Comment by anonimal** [comment] 2016-11-22 16:21
>I tried to run cmake -version and cmake --version, and then cmake --help and just cmake, and they all come back with "Segmentation fault."

It sounds like your system (or just cmake) is broken (not kovri-related).

I'm not a regular RPi user but if you followed the Debian kovri instructions precisely, and you somehow pulled non-ARM binaries, then that could explain why you can't even run cmake (there aren't rpi instructions for kovri yet).

Are you 100% sure you are *only* apt-pinning from `deb http://mirrordirector.raspbian.org/raspbian/ jessie main contrib non-free rpi` <-- with trailing `rpi` (for both `stable` and `testing` and that it's appropriately updated? If so, consider removing/cleaning/installing cmake and let's see what happens.

**Comment by anonimal** [comment] 2016-11-22 16:25
Side-note (unrelated to segfault): notice in the build instructions `a minimum of 1 GiB of RAM is suggested for build environments`. With that said, if you fix your system then I'd advise to also increase your swap space (maybe to 2GiB) if possible.

**Comment by anonimal** [comment] 2016-11-23 15:33
> +i2p-relay | {-_Slack} <scoobybejesus> i checked `cmake --help` and still got Segmentation fault.  Same with all `cmake` commands.

Discussed further on IRC. Closing as not kovri related.

@scoobybejesus if you fix cmake and you discover any further build issues, you can reopen this issue and/or ask on IRC.

**Closed by anonimal** 2016-11-23 15:33 UTC
Labels: info needed
