### ISSUE TITLE
SIGSEGV on ^C when starting up

### ISSUE THREAD

**Issue by moneromooo** [monero-project/kovri#386] opened 2016-10-02 19:26 UTC
**By submitting this issue, I confirm the following:**
- I have read and understood the [contributor guide](https://github.com/monero-project/kovri/blob/master/doc/CONTRIBUTING.md).
- I have checked that the issue I am reporting can be replicated or that the feature I am suggesting is not present.
- I have checked opened or recently closed [pull requests](https://github.com/monero-project/kovri/pulls) for existing solutions/implementations to my issue/suggestion.

_Place an X inside the bracket to confirm_
- [ ] I confirm.

---

_Enter your issue here_

Different issue thab 342, says EinMByte.

Stack: https://paste.fedoraproject.org/441937/47543635/
Log: https://paste.fedoraproject.org/441934/47543631/

**Comment by anonimal** [comment] 2016-10-02 19:38
Yes, thanks for reporting @moneromooo. It looks like an old issue but we've never got to reporting.

**Comment by anonimal** [comment] 2016-11-19 17:41
@moneromooo the links are dead so don't know the details but I can no longer reproduce anyway (was fixed in #466).

If a new startup issue appears, I'll open a new ticket. In the future, please attach backtrace and logs if you can, thanks.

**Closed by anonimal** 2016-11-19 17:41 UTC
Labels: bug
